// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nmqphhhmufayltamlsot.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5tcXBoaGhtdWZheWx0YW1sc290Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzMzk4MjAsImV4cCI6MjA2ODkxNTgyMH0.kGadVmfSLDxBIxsoqA550WHwR-oHqiC8eMTDM8K1nvg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});